---
- name: create a user foldre
  hosts: 172.31.18.121
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"

#previosly created cd host_vars---a: ch1
                                  b: 14ch
                                  c: /tmp/ch1
                                  d: 1414
                                  e: /bin/bash
---> ansible-playbook host_vars.yml -b

