---
- name: check os info
  hosts: all
  tasks:
    - name: capter os name
      debug:
        msg: "{{ansible_distribution}}"
    - name: check version
      debug:
        msg: "{{ansible_distribution_version}}"

# debug is used to information finds of OS and Version
--> ansible-playbook os-information-plb.yml -b
