---
- name: implement tags
  hosts: all
  tasks:
    - name: tree install
      apt:
        name: tree
        state: present
      tags: tree_install
    - name: create user
      user:
        name: chandra1
        password: 15554
        uid: 6643
      tags: create_user
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp

--> ansible-playbook plb-tags.yml -b
#install all modules
--> ansible-playbook plb-tags.yml --tags="tagged" -b
#only installed tags gived modules
--> ansible-playbook plb-tags.yml --tags="untagged" -b
#with out tags modules can be installed remain not installed
--> ansible-playbook plb-tags.yml --tags="tree_install" -b
#seecific path to to gives in tags run only specicic taged module
