---
- name: error handlers
  hosts: all
  tasks:
    - block:
        - name: git install apt 
          apt: 
            name: git
            state: present
      rescue:
        - name: git insatll yum
          yum:
            name: git
            state: present
      always:
        - name: disply sucess msg
          debug:
            msg: "git install"
