---
- name: install apache
  hosts: all
  tasks:
    - name: install apache2
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: apache2,b: present,c: no}
      notify: check url responce
    - name: ceat index.html
      copy:
        content: "deployment file can be achived"
        dest: /var/www/html/index.xml
      notify: restart apache
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
    - name: check url responce
      uri:
        url: "{{item}}"
      with_items:
        - http://172.31.18.121

--> ansible-playbook plb-handler2.yml -b
#it can used to module and its like a task but will only run when called by a notifier in another task
