---
- name: implement tags
  hosts: all
  tasks:
    - name: tree install
      apt:
        name: tree
        state: present
      tags: tree_install
    - name: create user
      user:
        name: chandra1
        password: 15554
        uid: 6643
      tags: create_user
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp

#tags is used to specific moules runs
--> ansuble-playbook plb-tags.yml --tags="tagged" -b
# only run tags conditions
--> ansible-playbook plb-tags.yml --tags="untagged" -b
# it time runs not mension tags
--> ansible-playbook plb-tags.yml --tags="create_user" -b
#specific taged module gives to runs single module
