---
- name: create git
  hosts: all
  tasks:
    - name: git/maven insatll
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
      with_items:
        - {a: git,b: present}
        - {a: maven,b: present}

#two images install in multi images used with_items
---> ansible-playbook plb-with_items.yml -b
