---
- name: install software applications
  hosts: all
  tasks:
    - name: install/uninstall
      apt:
        name: "{{a}}"
        state: "{{n}}"
        update_cache: "{{c}}"

#used in vars condition in different application in cmd "--extra-vars"
--> ansible-playbook plb6.yml --extra-vars 'a=git b=present c=no' -b
