---
- name: install software applications
  hosts: all
  tasks:
    - name: install/uninstall
      apt:
        name: "{{a}}"
        state: "{{n}}"
        update_cache: "{{c}}"


ansible-playbook plb6.yml --extra-vars 'a=tree n=present c=no' -b
