---
- name: user create
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
    - name: create directory
      file:
        name: "{{e}}"
        state: "{{f}}"
