---
- name: install/uninstall application
  hosts: all
  vars: 
    - a: tomcat9
    - b: present
    - c: no
  tasks:
    - name: install tom
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

 #its the vars file but directly gives in  vars place
 --> ansible-playbook plb8.yml -b

