---
- name: install/uninstall
  hosts: all
  tasks:
    - name: apache install
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"


ansible-playbook plb9.yml --extra-vars 'a=apache2 b=present c=no' -b
