---
- name: check folder f1 byt not crate f1
  hosts: all
  tasks:
    - name: check for f1
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: disply output 
      debug:
        var: a
    - name: create f1 not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
