---
- name: apache install multi child play books
  hosts: all
  tasks:
    - name: install apache
      include: "{{item}}"
      with_items:
        - install.yml
        - restart.yml
        - index.yml
        - pouse.yml
        - url.yml
...

#it's the group_var programm
main ues of multi chaild books runs once time used include
---> ansible-playbook var_include.yml
