---
- name: config apache in ubuntu and httpd in redhat
  hosts: all
  tasks:
    - name: install apache in ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install httpd in redhat
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: restart apache on ubuntu
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: restart httpd on redhat
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: chech responce apache/httpd all managed nodes
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.28.99
        - http://172.31.18.121
