---
- name: implement when
  hosts: all
  vars:
    - a: 20
  tasks:
    - name: copt passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
      when: a == 10

#this condition in when a==10 but vars in a=20 its false condition
--> ansible-playbook when2-plb.yml -b
