---
- name: install git in ubuntu/redhat
  hosts: all
  tasks:
    - name: install git in ubuntu
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install git in redhat
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"

      # it can used in when condition to different os is also runs specific
      anible_distribution == "RedHat" another os "Ubuntu" which os present in instances runs condition
      remain os skipped not comes error
      ---> ansible-playbook when-redhat.yml -b
