---
- name: install git in apt/yum
  hosts: all
  tasks: 
    - name: install git in apt
      apt:
        name: git
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: install git on yum
      yum:
        name: git
        state: present
      when: ansible_distribution == "RedHat"

# it can used by when condition true or false conditions converted
this case in ubuntun os runs but another os gives yum module os redhat not in this m/c
these time in when condition works to skipped redhat modules only runs ubuntun os based modules
--->ansible-playbook when3-plb.yml -b
